# Generated by Django 4.2.7 on 2024-02-16 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LITReview', '0003_critique_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Critique',
            new_name='Review',
        ),
    ]
