# Generated by Django 4.2.7 on 2024-02-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LITReview', '0004_rename_critique_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='image',
            new_name='images',
        ),
    ]
